# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

pool:
  name: Gohan
  vmImage: 'ubuntu:20.04'

steps:

- task: Bash@3
  displayName: 'Workaround: Set environment variables manually'
  inputs:
    targetType: 'inline'
    script: |
      cd ~
      echo "##vso[task.setvariable variable=HOME]$(pwd)"
      echo "##vso[task.setvariable variable=USER]$(whoami)"
      echo "##vso[task.setvariable variable=JAVA_HOME_8_X64]/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64"
      echo "##vso[task.setvariable variable=JAVA_HOME_11_X64]/usr/lib/jvm/adoptopenjdk-11-hotspot-amd64"
      echo "##vso[task.setvariable variable=JAVA_HOME]/usr/lib/jvm/adoptopenjdk-11-hotspot-amd64"

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '8'
    jdkArchitectureOption: 'x86'
    jdkSourceOption: 'PreInstalled'
- task: Gradle@2
  inputs:
    workingDirectory: '' #alterar a workdir, aqui é a pasta raiz
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug test'
  displayName: gradlew assembleDebug test

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'
  displayName: Copy .apk files to artifact staging directory

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'drop'
    artifactType: 'container'
  displayName: Publish artifacts