# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

pool:
  name: Gohan
  vmImage: 'ubuntu:20.04'

steps:
- script: |
    which java
    java -version
    echo JAVA_HOME_8_x86=$JAVA_HOME_8_x86
    echo JAVA_HOME=$JAVA_HOME
    export JAVA_HOME_8_X86=/etc/alternatives/jre_1.8.0_openjdk/
    javac
  displayName: "Set java version"

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '8'
    jdkArchitectureOption: 'x86'
    jdkSourceOption: 'PreInstalled'
- task: Gradle@2
  inputs:
    workingDirectory: '' #alterar a workdir, aqui é a pasta raiz
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug test'
  displayName: gradlew assembleDebug test

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'
  displayName: Copy .apk files to artifact staging directory

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'drop'
    artifactType: 'container'
  displayName: Publish artifacts